// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dagnys.api.Data;

#nullable disable

namespace dagnys.api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250102110548_added rawmaterial and some other changes")]
    partial class addedrawmaterialandsomeotherchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("dagnys.api.Entities.RawMaterial", b =>
                {
                    b.Property<int>("RawMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("TEXT");

                    b.HasKey("RawMaterialId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("dagnys.api.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("dagnys.api.Entities.SupplierRawMaterial", b =>
                {
                    b.Property<int>("SupplierRawMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierRawMaterialId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("SupplierRawMaterialId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("SupplierRawMaterialId1");

                    b.ToTable("SupplierRawMaterials");
                });

            modelBuilder.Entity("dagnys.api.Entities.SupplierRawMaterial", b =>
                {
                    b.HasOne("dagnys.api.Entities.Supplier", "Supplier")
                        .WithMany("SupplierRawMaterials")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dagnys.api.Entities.SupplierRawMaterial", null)
                        .WithMany("SupplierRawMaterials")
                        .HasForeignKey("SupplierRawMaterialId1");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("dagnys.api.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierRawMaterials");
                });

            modelBuilder.Entity("dagnys.api.Entities.SupplierRawMaterial", b =>
                {
                    b.Navigation("SupplierRawMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
